# Generated by Django 2.1.5 on 2020-08-12 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0008_auto_20200812_1605'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_verified', models.BooleanField(default=False, verbose_name='kyc status')),
                ('aadhar', models.FileField(upload_to='aadhar_images')),
                ('pan', models.FileField(upload_to='pan_images')),
                ('gts', models.FileField(upload_to='gts')),
                ('registration', models.FileField(upload_to='registration')),
                ('manager', models.CharField(max_length=75)),
                ('manage_mobile', models.IntegerField()),
                ('manager_email', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
