# Generated by Django 2.1.5 on 2020-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_changepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='prof1.jpg', upload_to='profile_image'),
        ),
    ]
