# Generated by Django 2.1.5 on 2020-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200707_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='prof1.jpeg', upload_to='profile_image'),
        ),
    ]
