# Generated by Django 2.1.5 on 2020-08-30 12:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined',
            field=jsonfield.fields.JSONField(default=list, null=True),
        ),
    ]
