# Generated by Django 2.1.5 on 2020-08-30 13:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200830_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
