# Generated by Django 2.1.5 on 2020-08-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200707_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_dealer',
            field=models.BooleanField(default=False, verbose_name='dealer status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_user',
            field=models.BooleanField(default=True, verbose_name='user status'),
        ),
    ]
