# Generated by Django 2.1.5 on 2020-08-10 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_auto_20200810_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_verified', models.BooleanField(default=False, verbose_name='kyc status')),
                ('aadhar', models.FileField(upload_to='aadhar_images')),
                ('pan', models.FileField(upload_to='pan_images')),
                ('gts', models.FileField(upload_to='gts')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
