# Generated by Django 2.1.5 on 2020-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200812_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='subscription status'),
        ),
    ]
