# Generated by Django 2.1.5 on 2020-08-27 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, null=True)),
                ('brand', models.CharField(max_length=25, null=True)),
                ('version', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('image', models.CharField(max_length=100)),
                ('mileage', models.IntegerField(null=True)),
                ('fuel_type', models.CharField(max_length=20, null=True)),
                ('seating_capacity', models.IntegerField(null=True)),
                ('body_style', models.CharField(max_length=20, null=True)),
                ('fuel_tank_capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now=True, db_index=True)),
                ('time', models.TimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('document', models.FileField(blank=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom'),
        ),
    ]
